#!/bin/bash

# Fail fast and verbosely
set -eox pipefail

# Clean up
make -f HOHQMesh.mak clean

# Build test suite
make -f HOHQMesh.mak -j 2 F90=$F90 FFLAGS="-cpp --coverage -O0" LDFLAGS="--coverage"

# Reset counters
lcov --directory . --zerocounters

# Run tests
./HOHQMesh -test

# Process coverage
lcov --directory . --capture --output-file lcov.info
