#!/bin/bash

# Fail fast and verbosely
set -eox pipefail

# Clean up
make clean

# Build test suite
make -j 2 F90=$F90 FFLAGS="-cpp --coverage -O0" LDFLAGS="--coverage"

# Reset counters
lcov --directory Source/ --no-external --zerocounters

# Run tests
./HOHQMesh -test

# Process coverage
lcov --directory Source/ --no-external --capture --output-file lcov.info
