#!/bin/bash
set -exo pipefail

# Clean out possibly existing FTObjectLibrary to ensure a clean bootstrap
rm -rf Contrib/FTObjectLibrary

# Clone FTObjectLibrary into Contrib
# TODO: change back to main once TypeMods2 is merged
git clone --branch TypeMods2 https://github.com/trixi-framework/FTObjectLibrary.git Contrib/FTObjectLibrary
