#!/bin/bash

# Fail fast and verbosely
set -eo pipefail

# Check that a version has been provided
if [ $# -eq 0 ]; then
  echo "ERROR: missing argument: version number" >&2
  exit 2
fi
version="$1"
echo "#########################################################"
echo "# Creating release tarball for HOHQMesh v$version..."
echo "#########################################################"
echo

# Clean up
printf "Clean up... "
make clean -s
echo "OK"

# Ensure that there are no uncommitted files/directories *except* the FTOL sources
printf "Ensure directory is clean and FTObjectLibrary is present... "
if [[ "$(git status --ignored --porcelain | grep -v '.DS_Store')" != "!! Contrib/FTObjectLibrary/" ]]; then
  echo "ERROR: directory is not clean or missing the FTObjectLibrary directory" >&2
  git status --ignored --porcelain
  exit 2
fi
echo OK

# Create temporary directory in a portable way
# Xref: https://unix.stackexchange.com/a/84980
printf "Create temporary directory... "
tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'hohqmesh-release')
echo "OK"

# Copy current directory to temporary directory
releasename="HOHQMesh-v$version"
releasedir="$tmpdir/$releasename"
printf "Copy current directory $(pwd) to $releasedir... "
cp -r "$(pwd)" "$releasedir"
echo "OK"

# Delete .git directories
printf "Delete .git directories for HOHQMesh and FTObjectLibrary... "
rm -rf "$releasedir/.git" "$releasedir/Contrib/FTObjectLibrary/.git"
echo "OK"

# Delete .DS_Store files (relevant on macOS only)
printf "Delete .DS_Store files... "
find "$releasedir" -name .DS_Store -exec rm {} \;
echo "OK"

# Create file with version info
printf "Create VERSION file with version information... "
echo $version > "$releasedir/VERSION"
echo "OK"

# Create tarball
tarball="$releasename.tar.gz"
printf "Create release tarball '$tarball'... "
tar czf "$tarball" -C "$tmpdir" "$releasename"
echo "OK"

# Remove temporary directory
printf "Remove temporary directory $tmpdir... "
rm -rf "$tmpdir"
echo "OK"

echo
echo "#########################################################"
echo "# done!"
echo "#########################################################"
echo
echo "$tarball"
