#!/bin/bash

# Fail fast and verbosely
set -eox pipefail

# Clean up
make clean

# Build test suite
make -j 2 FC=$FC FFLAGS="-cpp --coverage -O0" LDFLAGS="--coverage"

# Reset counters
lcov --directory . --exclude '*/FTObjectLibrary/*' --zerocounters

# Run tests
./HOHQMesh -test

# Exercise command line arguments
./Utilities/exercisecommandlineargs

# Process coverage
lcov --directory . --exclude '*/FTObjectLibrary/*' --capture --output-file lcov.info
