#!/bin/bash

# Fail fast and verbosely
set -eo pipefail

# Check that a version has been provided
if [ $# -eq 0 ]; then
  echo "ERROR: missing argument: release tarball" >&2
  exit 2
fi
tarball="$1"
echo "#########################################################"
echo "# Testing release tarball $tarball..."
echo "#########################################################"
echo

# Create temporary directory in a portable way
# Xref: https://unix.stackexchange.com/a/84980
printf "Create temporary directory... "
tmpdir=$(mktemp -d 2>/dev/null || mktemp -d -t 'hohqmesh-release')
echo "OK"

# Unpack tarball
printf "Unpack $tarball to $tmpdir... "
tar xf "$tarball" -C "$tmpdir"
echo "OK"

# Change directory to release directory
cd "$tmpdir"/HOHQMesh-*

# Build HOHQMesh
printf "Build HOHQMesh... "
if [ -z "$F90" ]; then
  make -j 2 -s
else
  make -j 2 -s F90=$F90
fi
echo "OK"

# Run tests
printf "Run tests... "
./HOHQMesh -test >/dev/null 2>&1
echo "OK"

# Remove temporary directory
printf "Remove temporary directory $tmpdir... "
rm -rf "$tmpdir"
echo "OK"

echo
echo "#########################################################"
echo "# done!"
echo "#########################################################"
