#!/bin/bash

set -exo pipefail

cp ../README.md docs/index.md
cp ../AUTHORS.md docs/authors.md
cp ../LICENSE.md docs/license.md
cp README.md docs/building-the-documentation.md

sed -i.bak "s/\[AUTHORS.md\](AUTHORS.md)/the [Authors](authors.md) section/" docs/index.md
sed -i.bak "s/\[LICENSE.md\](LICENSE.md)/the [License](license.md) section/" docs/index.md
sed -i.bak "s/\[gallery\](Documentation\/Docs\/Gallery.md)/\[gallery\](a-hohqmesh-mesh-gallery)/" docs/index.md
sed -i.bak "s/\[LICENSE.md\](LICENSE.md)/the [License](license.md) section/" docs/authors.md
sed -i.bak "s/\[AUTHORS.md\](AUTHORS.md)/[Authors](authors.md)/" docs/license.md

rm -f docs/index.md.bak
rm -f docs/authors.md.bak
rm -f docs/license.md.bak
